INSERT INTO employees (id, email, first_name, last_name, role) VALUES (1, 'donald@example.com', 'Donald', 'Trump', 'PROJECT_MANAGER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (2, 'angela@example.com', 'Angela', 'Merkel', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (3, 'boris@example.com', 'Boris', 'Johnson', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (4, 'vladimir@example.com', 'Vladimir', 'Putin', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (5, 'emmanuel@example.com', 'Emmanuel', 'Macron', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (6, 'justin@example.com', 'Justin', 'Trudeau', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (7, 'greta@example.com', 'Greta', 'Thunberg', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (8, 'kim@example.com', 'Kim', 'Jong Un', 'PROJECT_MANAGER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (9, 'xi@example.com', 'Xi', 'Jinping', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (10, 'shinzo@example.com', 'Shinzo', 'Abe', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (11, 'mikhailkarpov@guiseppe.com', 'Guiseppe', 'Conte', 'TEAM_MEMBER');
INSERT INTO employees (id, email, first_name, last_name, role) VALUES (12, 'jair@example.com', 'Jair', 'Messias Bolsonaro', 'TEAM_MEMBER');